check_task:
        compile_script:
                - ./configure
                - make -j4
        test_jail_prep_script:
                - make -C test prep
        check_script: make -sj4 check || { cat test/test-suite.log; exit 1; }
        check_stock_script: make -sj4 check SH=/bin/sh || { cat test/test-suite.log; exit 1; }
        matrix:
                - name: freebsd11-amd64
                  freebsd_instance:
                    image: freebsd-11-2-release-amd64
                - name: freebsd12-amd64
                  freebsd_instance:
                    image: freebsd-12-0-release-amd64
                - name: freebsd13-amd64
                  freebsd_instance:
                    image_family: freebsd-13-0-snap
